Updated curl

diff --git a/curl/curl/maketgz b/curl/curl/maketgz
--- a/curl/curl/maketgz
+++ b/curl/curl/maketgz
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/bin/sh
 # Script to build release-archives with. Note that this requires a checkout
 # from git and you should first run ./buildconf and build curl once.
 #
@@ -9,11 +9,11 @@
 #                            | (__| |_| |  _ <| |___
 #                             \___|\___/|_| \_\_____|
 #
-# Copyright (C) 1998 - 2017, Daniel Stenberg, <daniel@haxx.se>, et al.
+# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
 #
 # This software is licensed as described in the file COPYING, which
 # you should have received as part of this distribution. The terms
-# are also available at https://curl.haxx.se/docs/copyright.html.
+# are also available at https://curl.se/docs/copyright.html.
 #
 # You may opt to use, copy, modify, merge, publish, distribute and/or sell
 # copies of the Software, and permit persons to whom the Software is
@@ -21,6 +21,8 @@
 #
 # This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 # KIND, either express or implied.
+#
+# SPDX-License-Identifier: curl
 #
 ###########################################################################
 
@@ -32,8 +34,8 @@ if [ -z "$version" ]; then
 fi
 
 if [ "xonly" = "x$2" ]; then
-    echo "Setup version number only!"
-    only=1
+  echo "Setup version number only!"
+  only=1
 fi
 
 libversion="$version"
@@ -41,53 +43,64 @@ libversion="$version"
 # we make curl the same version as libcurl
 curlversion=$libversion
 
-major=`echo $libversion |cut -d. -f1 | sed -e "s/[^0-9]//g"`
-minor=`echo $libversion |cut -d. -f2 | sed -e "s/[^0-9]//g"`
-patch=`echo $libversion |cut -d. -f3 | cut -d- -f1 | sed -e "s/[^0-9]//g"`
+major=`echo $libversion | cut -d. -f1 | sed -e "s/[^0-9]//g"`
+minor=`echo $libversion | cut -d. -f2 | sed -e "s/[^0-9]//g"`
+patch=`echo $libversion | cut -d. -f3 | cut -d- -f1 | sed -e "s/[^0-9]//g"`
 
 if test -z "$patch"; then
-    echo "invalid version number? needs to be z.y.z"
-    exit
+  echo "invalid version number? needs to be z.y.z"
+  exit
 fi
+
+#
+# As a precaution, remove all *.dist files that may be lying around, to reduce
+# the risk of old leftovers getting shipped. The root 'Makefile.dist' is the
+# exception.
+echo "removing all old *.dist files"
+find . -name "*.dist" -a ! -name Makefile.dist -exec rm {} \;
 
 numeric=`perl -e 'printf("%02x%02x%02x\n", '"$major, $minor, $patch);"`
 
 HEADER=include/curl/curlver.h
 CHEADER=src/tool_version.h
 PLIST=lib/libcurl.plist
+PLISTO=$PLIST
 
 if test -z "$only"; then
-    ext=".dist"
-    # when not setting up version numbers locally
-    for a in $HEADER $CHEADER $PLIST; do
-        cp $a "$a$ext"
-    done
-    HEADER="$HEADER$ext"
-    CHEADER="$CHEADER$ext"
-    PLIST="$PLIST$ext"
+  ext=".dist"
+  # when not setting up version numbers locally
+  for a in $HEADER $CHEADER $PLIST; do
+    cp $a "$a$ext"
+  done
+  HEADER="$HEADER$ext"
+  CHEADER="$CHEADER$ext"
+  PLIST="$PLIST$ext"
 fi
 
-# requires a date command that knows -u for UTC time zone
-datestamp=`LC_TIME=C date -u`
+# requires a date command that knows + for format
+datestamp=`date +"%F"`
 
 # Replace version number in header file:
-sed -i -e 's/^#define LIBCURL_VERSION .*/#define LIBCURL_VERSION "'$libversion'"/g' \
+sed -i.bak \
+    -e 's/^#define LIBCURL_VERSION .*/#define LIBCURL_VERSION "'$libversion'"/g' \
     -e 's/^#define LIBCURL_VERSION_NUM .*/#define LIBCURL_VERSION_NUM 0x'$numeric'/g' \
     -e 's/^#define LIBCURL_VERSION_MAJOR .*/#define LIBCURL_VERSION_MAJOR '$major'/g' \
     -e 's/^#define LIBCURL_VERSION_MINOR .*/#define LIBCURL_VERSION_MINOR '$minor'/g' \
     -e 's/^#define LIBCURL_VERSION_PATCH .*/#define LIBCURL_VERSION_PATCH '$patch'/g' \
     -e "s/^#define LIBCURL_TIMESTAMP .*/#define LIBCURL_TIMESTAMP \"$datestamp\"/g" \
- $HEADER
+    $HEADER
+rm -f "$HEADER.bak"
 
 # Replace version number in header file:
-sed -i 's/#define CURL_VERSION .*/#define CURL_VERSION "'$curlversion'"/g' $CHEADER
+sed -i.bak 's/#define CURL_VERSION .*/#define CURL_VERSION "'$curlversion'"/g' $CHEADER
+rm -f "$CHEADER.bak"
 
 # Replace version number in plist file:
-sed -i "s/7\.12\.3/$libversion/g" $PLIST
+sed "s/@CURL_PLIST_VERSION@/$curlversion/g" < $PLISTO.in >$PLIST
 
 if test -n "$only"; then
-    # done!
-    exit;
+  # done!
+  exit;
 fi
 
 echo "curl version $curlversion"
@@ -95,8 +108,7 @@ echo "libcurl version $libversion"
 echo "libcurl numerical $numeric"
 echo "datestamp $datestamp"
 
-findprog()
-{
+findprog() {
   file="$1"
   for part in `echo $PATH| tr ':' ' '`; do
     path="$part/$file"
@@ -137,7 +149,10 @@ fi
 #
 
 echo "update man pages"
-./scripts/updatemanpages.pl $version
+./scripts/updatemanpages.pl $version >/dev/null
+
+# make the generated file newer than the man page
+touch src/tool_hugehelp.c
 
 ############################################################################
 #
@@ -156,6 +171,12 @@ git log --pretty=fuller --no-color --date=short --decorate=full -1000 | ./script
 echo "make dist"
 targz="curl-$version.tar.gz"
 make -sj dist VERSION=$version
+res=$?
+
+if test "$res" != 0; then
+    echo "make dist failed"
+    exit 2
+fi
 
 ############################################################################
 #
@@ -168,19 +189,18 @@ gzip -dc $targz | bzip2 --best > $bzip2
 
 ############################################################################
 #
-# Now make an lzma archive from the tar.gz original
+# Now make an xz archive from the tar.gz original
 #
 
-lzma="curl-$version.tar.lzma"
-echo "Generating $lzma"
-gzip -dc $targz | lzma --best - > $lzma
+xz="curl-$version.tar.xz"
+echo "Generating $xz"
+gzip -dc $targz | xz -6e - > $xz
 
 ############################################################################
 #
 # Now make a zip archive from the tar.gz original
 #
-makezip ()
-{
+makezip() {
   rm -rf $tempdir
   mkdir $tempdir
   cd $tempdir
@@ -199,7 +219,7 @@ makezip
 echo "------------------"
 echo "maketgz report:"
 echo ""
-ls -l $targz $bzip2 $zip $lzma
+ls -l $targz $bzip2 $zip $xz
 
 echo "Run this:"
-echo "gpg -b -a $targz && gpg -b -a $bzip2 && gpg -b -a $zip && gpg -b -a $lzma"
+echo "gpg -b -a $targz && gpg -b -a $bzip2 && gpg -b -a $zip && gpg -b -a $xz"
